"""Host-side unit test for the USB Audio decoding and stream-selection helpers.

The helpers are ``inline`` free functions in ``src/EspUsbHost.h``, but that header
pulls in Arduino and the ESP USB host stack and cannot be compiled on the host.
Like the keymap test, this one extracts the pieces it needs from the real source
at run time instead of duplicating them, so the assertions run against the
production code:

* the ``ESP_USB_HOST_MAX_AUDIO_SAMPLE_RATES`` and
  ``ESP_USB_HOST_AUDIO_PROTOCOL_*`` constants
* ``struct EspUsbHostAudioVolumeRange`` and
  ``struct EspUsbHostAudioFeatureUnitLayout``
* every ``espUsbHostAudio*`` helper used by the Feature Unit / Clock Source /
  feedback-endpoint paths
* ``struct EspUsbHostAudioStreamInfo`` and the format-selection helpers that
  ``audioInputStart()`` / ``audioOutputStart()`` delegate to

These are concatenated into ``output/espusbhost_audio_real.h`` and compiled with
``audio_uac_test.cpp``.
"""

import re
import subprocess
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / ".." / ".." / ".." / "src"

# Extracted in this order: later helpers call earlier ones.
FUNCTIONS = [
    "inline EspUsbHostAudioFeatureUnitLayout espUsbHostAudioFeatureUnitLayout(",
    "inline bool espUsbHostAudioFeatureHasControl(",
    "inline bool espUsbHostAudioFeatureControlWritable(",
    "inline bool espUsbHostAudioIsFeedbackEndpoint(",
    "inline uint32_t espUsbHostAudioReadU32(",
    "inline uint32_t espUsbHostAudioDecodeFeedbackQ16(",
    "inline uint32_t espUsbHostAudioFeedbackSampleRate(",
    "inline bool espUsbHostAudioFeedbackRatePlausible(",
    "inline size_t espUsbHostAudioRangeDeclaredCount(",
    "inline size_t espUsbHostAudioRangeSubRangeCount(",
    "inline size_t espUsbHostAudioDecodeSampleRateRange(",
    "inline bool espUsbHostAudioDecodeVolumeRange(",
    # Stream selection: each helper calls the ones above it.
    "inline bool espUsbHostAudioStreamSupportsSampleRate(",
    "inline bool espUsbHostAudioStreamCandidateRateExists(",
    "inline size_t espUsbHostAudioStreamCandidateSampleRates(",
    "inline int espUsbHostAudioStreamScore(",
    "inline EspUsbHostAudioStreamSelection espUsbHostSelectAudioStreamForFormat(",
]

STRUCTS = [
    "EspUsbHostAudioVolumeRange",
    "EspUsbHostAudioFeatureUnitLayout",
    "EspUsbHostAudioStreamInfo",
    "EspUsbHostAudioStreamSelection",
]

CONSTANTS = [
    "ESP_USB_HOST_MAX_AUDIO_SAMPLE_RATES",
    "ESP_USB_HOST_AUDIO_PROTOCOL_UAC1",
    "ESP_USB_HOST_AUDIO_PROTOCOL_UAC2",
]


def _brace_match(text: str, signature: str) -> str:
    """Return the full definition (signature + body) for a declaration, located by
    a substring of its signature and delimited by brace matching."""
    start = text.index(signature)
    open_brace = text.index("{", start)
    depth = 0
    for i in range(open_brace, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                end = text.index(";", i) + 1 if text[start:].startswith("struct") else i + 1
                return text[start:end]
    raise AssertionError(f"unbalanced braces after {signature!r}")


def _generate_real_header(dest: Path) -> None:
    host_h = (SRC / "EspUsbHost.h").read_text()

    parts = [
        "// GENERATED by test_audio_uac.py from src/EspUsbHost.h.",
        "// Do not edit; do not commit.",
        "#pragma once",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
    ]

    for name in CONSTANTS:
        match = re.search(
            r"^static constexpr \w+ " + name + r" = [^;]+;", host_h, re.M
        )
        assert match, f"{name} not found in EspUsbHost.h"
        parts.append(match.group(0))
    parts.append("")

    for name in STRUCTS:
        parts.append(_brace_match(host_h, f"struct {name}\n"))
        parts.append("")

    for signature in FUNCTIONS:
        parts.append(_brace_match(host_h, signature))
        parts.append("")

    dest.write_text("\n".join(parts))


def test_audio_uac_decoding():
    output = HERE / "output"
    output.mkdir(exist_ok=True)
    _generate_real_header(output / "espusbhost_audio_real.h")

    binary = output / "audio_uac_test"
    compile_result = subprocess.run(
        [
            "g++",
            "-std=c++17",
            "-Wall",
            "-Wextra",
            "-I", str(output),  # espusbhost_audio_real.h
            str(HERE / "audio_uac_test.cpp"),
            "-o", str(binary),
        ],
        capture_output=True,
        text=True,
    )
    assert compile_result.returncode == 0, compile_result.stderr

    run_result = subprocess.run([str(binary)], capture_output=True, text=True)
    assert run_result.returncode == 0, run_result.stdout + run_result.stderr
