def test_host_logic(dut):
    dut.expect_exact("TEST_BEGIN host_logic")
    dut.expect_exact("PASS key_us_a")
    dut.expect_exact("PASS key_us_shift_a")
    dut.expect_exact("PASS key_us_shift_2")
    dut.expect_exact("PASS key_jp_shift_2")
    dut.expect_exact("PASS keypad_1_shift_ignored")
    dut.expect_exact("PASS keypad_dot")
    dut.expect_exact("PASS keyboard_report_valid")
    dut.expect_exact("PASS keyboard_report_reserved_invalid")
    dut.expect_exact("PASS keyboard_report_keycode_invalid")
    dut.expect_exact("PASS keyboard_report_short_invalid")
    dut.expect_exact("PASS keyboard_press_a")
    dut.expect_exact("PASS keyboard_press_b_while_a_held")
    dut.expect_exact("PASS keyboard_release_b")
    dut.expect_exact("PASS keyboard_shift_a")
    dut.expect_exact("PASS mouse_idle_no_event")
    dut.expect_exact("PASS mouse_move_wheel")
    dut.expect_exact("PASS mouse_button_press")
    dut.expect_exact("PASS mouse_button_release")
    dut.expect_exact("PASS mouse_short_invalid")
    dut.expect_exact("PASS keyboard_led_none")
    dut.expect_exact("PASS keyboard_led_num")
    dut.expect_exact("PASS keyboard_led_caps")
    dut.expect_exact("PASS keyboard_led_scroll")
    dut.expect_exact("PASS keyboard_led_all")
    dut.expect_exact("TEST_END pass=24 fail=0")
    dut.expect_exact("OK")
