// Host-side unit tests for the HID usage -> 8-bit character conversion.
//
// This file is compiled and run on the host with g++ (no board required) by
// test_keymap.py. The layout enum, the keymap include list, and the two pure
// conversion functions (espUsbHostKeycodeToAscii / espUsbHostKeypadKeycodeToAscii)
// are extracted verbatim from the real library sources at test time and written
// to "espusbhost_keymap_real.h" in the build output directory, so these checks
// exercise the actual production tables and conversion logic - not a copy.
//
// Expected values follow each layout's national standard (Windows layout data;
// non-ASCII in ISO-8859-1, dead keys produce 0).

#include <cstdint>
#include <cstddef>
#include <cstdio>
#include <initializer_list>

// Generated by test_keymap.py: enum + keymap tables + conversion functions,
// all extracted from src/EspUsbHost.h and src/EspUsbHostHid.cpp.
#include "espusbhost_keymap_real.h"

namespace
{
int failures = 0;
constexpr uint8_t Shift = 0x02;   // Left Shift modifier bit
constexpr uint8_t AltGr = 0x40;   // Right Alt (AltGr) modifier bit

void check(const char *name, unsigned actual, unsigned expected)
{
  if (actual != expected)
  {
    std::printf("FAIL %-42s got 0x%02x expected 0x%02x\n", name, actual, expected);
    ++failures;
  }
}

uint8_t conv(
    uint8_t keycode,
    uint8_t modifiers,
    EspUsbHostKeyboardLayout layout,
    bool capsLock = false,
    bool numLock = false)
{
  return espUsbHostKeycodeToAscii(keycode, modifiers, layout, capsLock, numLock);
}

uint16_t convU(
    uint8_t keycode,
    uint8_t modifiers,
    EspUsbHostKeyboardLayout layout,
    bool capsLock = false,
    bool numLock = false)
{
  return espUsbHostKeycodeToUnicode(keycode, modifiers, layout, capsLock, numLock);
}
} // namespace

int main()
{
  const auto EnUs = ESP_USB_HOST_KEYBOARD_LAYOUT_EN_US;
  const auto DaDk = ESP_USB_HOST_KEYBOARD_LAYOUT_DA_DK;
  const auto DeDe = ESP_USB_HOST_KEYBOARD_LAYOUT_DE_DE;
  const auto EnGb = ESP_USB_HOST_KEYBOARD_LAYOUT_EN_GB;
  const auto EsEs = ESP_USB_HOST_KEYBOARD_LAYOUT_ES_ES;
  const auto FiFi = ESP_USB_HOST_KEYBOARD_LAYOUT_FI_FI;
  const auto FrCh = ESP_USB_HOST_KEYBOARD_LAYOUT_FR_CH;
  const auto FrFr = ESP_USB_HOST_KEYBOARD_LAYOUT_FR_FR;
  const auto HuHu = ESP_USB_HOST_KEYBOARD_LAYOUT_HU_HU;
  const auto ItIt = ESP_USB_HOST_KEYBOARD_LAYOUT_IT_IT;
  const auto JaJp = ESP_USB_HOST_KEYBOARD_LAYOUT_JA_JP;
  const auto NbNo = ESP_USB_HOST_KEYBOARD_LAYOUT_NB_NO;
  const auto NlNl = ESP_USB_HOST_KEYBOARD_LAYOUT_NL_NL;
  const auto PtBr = ESP_USB_HOST_KEYBOARD_LAYOUT_PT_BR;
  const auto PtPt = ESP_USB_HOST_KEYBOARD_LAYOUT_PT_PT;
  const auto SvSe = ESP_USB_HOST_KEYBOARD_LAYOUT_SV_SE;

  // Keypad handling is layout-independent.
  check("keypad / (numlock off)", conv(0x54, 0, EnUs, false, false), '/');
  check("keypad 1 (numlock on)", conv(0x59, 0, EnUs, false, true), '1');
  check("keypad 1 (numlock off)", conv(0x59, 0, EnUs, false, false), 0);

  // Guard: only extended layouts (ja_jp, pt_BR) may reach usage >= 0x80,
  // and never beyond 0x8f. Everything else above 0x7f returns 0.
  check("enUS out of range 0x87", conv(0x87, 0, EnUs), 0);
  check("ptBR out of range 0x90", conv(0x90, 0, PtBr), 0);
  check("jaJP out of range 0x90", conv(0x90, 0, JaJp), 0);

  // ja-JP (JIS). Comment-only fix upstream; data must be unchanged.
  check("jaJP shift 2", conv(0x1f, Shift, JaJp), '"');
  check("jaJP ro", conv(0x87, 0, JaJp), '\\');
  check("jaJP shift ro", conv(0x87, Shift, JaJp), '_');
  check("jaJP yen", conv(0x89, 0, JaJp), '\\');
  check("jaJP shift yen", conv(0x89, Shift, JaJp), '|');

  // nl-NL (Dutch, Windows KBDNE). Digit row shift characters.
  check("nlNL shift 2", conv(0x1f, Shift, NlNl), '"');
  check("nlNL shift 6", conv(0x23, Shift, NlNl), '&');
  check("nlNL shift 7", conv(0x24, Shift, NlNl), '_');
  check("nlNL shift 8", conv(0x25, Shift, NlNl), '(');
  check("nlNL shift 9", conv(0x26, Shift, NlNl), ')');
  check("nlNL shift 0", conv(0x27, Shift, NlNl), '\'');
  // Symbol keys.
  check("nlNL minus position", conv(0x2d, 0, NlNl), '/');
  check("nlNL shift minus position", conv(0x2d, Shift, NlNl), '?');
  check("nlNL equals position (degree)", conv(0x2e, 0, NlNl), 0xb0);
  check("nlNL shift equals (dead ~)", conv(0x2e, Shift, NlNl), 0);
  check("nlNL [ position (dead trema)", conv(0x2f, 0, NlNl), 0);
  check("nlNL ] position", conv(0x30, 0, NlNl), '*');
  check("nlNL shift ] position", conv(0x30, Shift, NlNl), '|');
  check("nlNL NUHS", conv(0x32, 0, NlNl), '<');
  check("nlNL shift NUHS", conv(0x32, Shift, NlNl), '>');
  check("nlNL ; position", conv(0x33, 0, NlNl), '+');
  check("nlNL shift ; position (plus-minus)", conv(0x33, Shift, NlNl), 0xb1);
  check("nlNL ' position (dead acute)", conv(0x34, 0, NlNl), 0);
  check("nlNL grave position", conv(0x35, 0, NlNl), '@');
  check("nlNL shift grave (section)", conv(0x35, Shift, NlNl), 0xa7);
  check("nlNL shift comma", conv(0x36, Shift, NlNl), ';');
  check("nlNL shift period", conv(0x37, Shift, NlNl), ':');
  check("nlNL slash position", conv(0x38, 0, NlNl), '-');
  check("nlNL shift slash position", conv(0x38, Shift, NlNl), '=');
  check("nlNL NUBS", conv(0x64, 0, NlNl), ']');
  check("nlNL shift NUBS", conv(0x64, Shift, NlNl), '[');

  // pt-BR (ABNT2). The previously-broken keys: International1 (/ and ?) and the
  // numpad comma, plus the cedilla and the slash-key-that-stays-semicolon.
  check("ptBR cedilla", conv(0x33, 0, PtBr), 0xe7);
  check("ptBR shift cedilla", conv(0x33, Shift, PtBr), 0xc7);
  check("ptBR slash key stays ;", conv(0x38, 0, PtBr), ';');
  check("ptBR shift slash key stays :", conv(0x38, Shift, PtBr), ':');
  check("ptBR International1 /", conv(0x87, 0, PtBr), '/');
  check("ptBR shift International1 ?", conv(0x87, Shift, PtBr), '?');
  check("ptBR keypad comma", conv(0x85, 0, PtBr), ',');

  // --- AltGr (Right Alt / level 3) ---
  // Mechanism: AltGr held on a key with no AltGr value falls back to base/Shift.
  // (Uses de_DE 'a', which has no AltGr value; the en_US table is a zero stub on
  // the host build so it cannot exercise character values here.)
  check("deDE AltGr a falls back to a", conv(0x04, AltGr, DeDe), 'a');
  check("deDE AltGr shift a falls back to A", conv(0x04, AltGr | Shift, DeDe), 'A');
  // de-DE (Windows KBDGR / DIN 2137 T1) AltGr layer.
  check("deDE AltGr q (@)", conv(0x14, AltGr, DeDe), '@');
  check("deDE AltGr m (micro)", conv(0x10, AltGr, DeDe), 0xb5);
  check("deDE AltGr 2 (superscript2)", conv(0x1f, AltGr, DeDe), 0xb2);
  check("deDE AltGr 3 (superscript3)", conv(0x20, AltGr, DeDe), 0xb3);
  check("deDE AltGr 7 ({)", conv(0x24, AltGr, DeDe), '{');
  check("deDE AltGr 8 ([)", conv(0x25, AltGr, DeDe), '[');
  check("deDE AltGr 9 (])", conv(0x26, AltGr, DeDe), ']');
  check("deDE AltGr 0 (})", conv(0x27, AltGr, DeDe), '}');
  check("deDE AltGr ss (backslash)", conv(0x2d, AltGr, DeDe), '\\');
  check("deDE AltGr + (tilde)", conv(0x30, AltGr, DeDe), '~');
  check("deDE AltGr < (pipe)", conv(0x64, AltGr, DeDe), '|');
  // AltGr wins over Shift on a key that has an AltGr value.
  check("deDE AltGr+shift q still @", conv(0x14, AltGr | Shift, DeDe), '@');
  // AltGr+E (=> EUR) is not representable in ISO-8859-1: falls back to base.
  check("deDE AltGr e unicode EUR", convU(0x08, AltGr, DeDe), 0x20ac);
  check("deDE AltGr e ascii 0 (EUR not Latin-1)", conv(0x08, AltGr, DeDe), 0);
  // Non-AltGr de-DE basics unaffected.
  check("deDE q", conv(0x14, 0, DeDe), 'q');
  check("deDE shift 7 (/)", conv(0x24, Shift, DeDe), '/');

  // fr-FR (AZERTY, Windows KBDFR) AltGr layer.
  check("frFR AltGr 0 (@)", conv(0x27, AltGr, FrFr), '@');
  check("frFR AltGr 4 ({)", conv(0x21, AltGr, FrFr), '{');
  check("frFR AltGr 5 ([)", conv(0x22, AltGr, FrFr), '[');
  check("frFR AltGr ) (])", conv(0x2d, AltGr, FrFr), ']');
  check("frFR AltGr = (})", conv(0x2e, AltGr, FrFr), '}');
  check("frFR AltGr 6 (pipe)", conv(0x23, AltGr, FrFr), '|');
  check("frFR AltGr 8 (backslash)", conv(0x25, AltGr, FrFr), '\\');
  check("frFR AltGr 2 (~)", conv(0x1f, AltGr, FrFr), '~');
  check("frFR AltGr 3 (#)", conv(0x20, AltGr, FrFr), '#');
  check("frFR AltGr 7 (backtick)", conv(0x24, AltGr, FrFr), '`');
  check("frFR AltGr 9 (^)", conv(0x26, AltGr, FrFr), '^');
  check("frFR AltGr e unicode EUR", convU(0x08, AltGr, FrFr), 0x20ac);
  check("frFR AltGr e ascii 0", conv(0x08, AltGr, FrFr), 0);
  // Non-AltGr fr-FR basics unaffected (AZERTY positions).
  check("frFR a position -> q", conv(0x04, 0, FrFr), 'q');
  check("frFR shift 2 -> 2", conv(0x1f, Shift, FrFr), '2');

  // es-ES (Windows KBDSP) AltGr layer.
  check("esES AltGr 2 (@)", conv(0x1f, AltGr, EsEs), '@');
  check("esES AltGr 1 (pipe)", conv(0x1e, AltGr, EsEs), '|');
  check("esES AltGr 3 (#)", conv(0x20, AltGr, EsEs), '#');
  check("esES AltGr 4 (~)", conv(0x21, AltGr, EsEs), '~');
  check("esES AltGr 6 (not-sign)", conv(0x23, AltGr, EsEs), 0xac);
  check("esES AltGr grave ([)", conv(0x2f, AltGr, EsEs), '[');
  check("esES AltGr + (])", conv(0x30, AltGr, EsEs), ']');
  check("esES AltGr acute ({)", conv(0x34, AltGr, EsEs), '{');
  check("esES AltGr cedilla (})", conv(0x32, AltGr, EsEs), '}');
  check("esES AltGr masculine (backslash)", conv(0x35, AltGr, EsEs), '\\');
  check("esES AltGr e unicode EUR", convU(0x08, AltGr, EsEs), 0x20ac);
  check("esES AltGr e ascii 0", conv(0x08, AltGr, EsEs), 0);
  // Base values on dead keys stay 0.
  check("esES grave dead key base 0", conv(0x2f, 0, EsEs), 0);

  // it-IT (Windows KBDIT) AltGr layer (sparse; { } are level-4, unsupported).
  check("itIT AltGr o-grave (@)", conv(0x33, AltGr, ItIt), '@');
  check("itIT AltGr a-grave (#)", conv(0x34, AltGr, ItIt), '#');
  check("itIT AltGr e-grave ([)", conv(0x2f, AltGr, ItIt), '[');
  check("itIT AltGr + (])", conv(0x30, AltGr, ItIt), ']');
  check("itIT AltGr e unicode EUR", convU(0x08, AltGr, ItIt), 0x20ac);
  check("itIT AltGr e ascii 0", conv(0x08, AltGr, ItIt), 0);
  // AltGr alone gives [ ]; AltGr+Shift (level 4) gives { }.
  check("itIT AltGr e-grave ([)", conv(0x2f, AltGr, ItIt), '[');
  check("itIT AltGr+Shift e-grave ({)", conv(0x2f, AltGr | Shift, ItIt), '{');
  check("itIT AltGr+Shift + (})", conv(0x30, AltGr | Shift, ItIt), '}');

  // nl-NL (Windows KBDNE / ReactOS kbdne.c) AltGr layer.
  check("nlNL AltGr 8 ({)", conv(0x25, AltGr, NlNl), '{');
  check("nlNL AltGr 9 (})", conv(0x26, AltGr, NlNl), '}');
  check("nlNL AltGr 7 (pound)", conv(0x24, AltGr, NlNl), 0xa3);
  check("nlNL AltGr 1 (superscript1)", conv(0x1e, AltGr, NlNl), 0xb9);
  check("nlNL AltGr 2 (superscript2)", conv(0x1f, AltGr, NlNl), 0xb2);
  check("nlNL AltGr 4 (quarter)", conv(0x21, AltGr, NlNl), 0xbc);
  check("nlNL AltGr 5 (half)", conv(0x22, AltGr, NlNl), 0xbd);
  check("nlNL AltGr 6 (three-quarters)", conv(0x23, AltGr, NlNl), 0xbe);
  check("nlNL AltGr m (micro)", conv(0x10, AltGr, NlNl), 0xb5);
  check("nlNL AltGr s (eszett)", conv(0x16, AltGr, NlNl), 0xdf);
  check("nlNL AltGr z (left guillemet)", conv(0x1d, AltGr, NlNl), 0xab);
  check("nlNL AltGr x (right guillemet)", conv(0x1b, AltGr, NlNl), 0xbb);
  check("nlNL AltGr c (cent)", conv(0x06, AltGr, NlNl), 0xa2);
  check("nlNL AltGr r (pilcrow)", conv(0x15, AltGr, NlNl), 0xb6);
  check("nlNL AltGr e unicode EUR", convU(0x08, AltGr, NlNl), 0x20ac);
  check("nlNL AltGr e ascii 0", conv(0x08, AltGr, NlNl), 0);
  // AltGr on a letter ignores CapsLock (returns the AltGr symbol).
  check("nlNL AltGr s with capslock", conv(0x16, AltGr, NlNl, true), 0xdf);

  // Nordic layouts (Windows / ReactOS kbdda/kbdno/kbdsw/kbdfi) share the
  // programmer AltGr row 2@ 3£ 7{ 8[ 9] 0} plus $ on 4.
  for (auto L : {DaDk, NbNo, SvSe, FiFi})
  {
    check("nordic AltGr 2 (@)", conv(0x1f, AltGr, L), '@');
    check("nordic AltGr 3 (pound)", conv(0x20, AltGr, L), 0xa3);
    check("nordic AltGr 4 ($)", conv(0x21, AltGr, L), '$');
    check("nordic AltGr 7 ({)", conv(0x24, AltGr, L), '{');
    check("nordic AltGr 8 ([)", conv(0x25, AltGr, L), '[');
    check("nordic AltGr 9 (])", conv(0x26, AltGr, L), ']');
    check("nordic AltGr 0 (})", conv(0x27, AltGr, L), '}');
    check("nordic AltGr m (micro)", conv(0x10, AltGr, L), 0xb5);
  }
  // da_DK / nb_NO / fi_FI: AltGr+5 = € (unicode), ascii 0. sv_SE: AltGr+5 = ¬.
  check("daDK AltGr 5 EUR unicode", convU(0x22, AltGr, DaDk), 0x20ac);
  check("daDK AltGr 5 ascii 0", conv(0x22, AltGr, DaDk), 0);
  check("svSE AltGr 5 (not-sign)", conv(0x22, AltGr, SvSe), 0xac);
  check("svSE AltGr e (not-sign)", conv(0x08, AltGr, SvSe), 0xac);
  check("daDK AltGr < (backslash)", conv(0x64, AltGr, DaDk), '\\');
  check("svSE AltGr + (backslash)", conv(0x2d, AltGr, SvSe), '\\');
  check("svSE AltGr < (pipe)", conv(0x64, AltGr, SvSe), '|');
  check("svSE AltGr diaeresis (~)", conv(0x30, AltGr, SvSe), '~');
  check("fiFI AltGr < (pipe)", conv(0x64, AltGr, FiFi), '|');

  // en-GB (Windows KBDUK): sparse AltGr — € on 4, broken bar on grave.
  check("enGB AltGr 4 EUR unicode", convU(0x21, AltGr, EnGb), 0x20ac);
  check("enGB AltGr 4 ascii 0", conv(0x21, AltGr, EnGb), 0);
  check("enGB AltGr grave (broken bar)", conv(0x35, AltGr, EnGb), 0xa6);

  // pt-PT (Windows KBDPO).
  check("ptPT AltGr 2 (@)", conv(0x1f, AltGr, PtPt), '@');
  check("ptPT AltGr 4 (section)", conv(0x21, AltGr, PtPt), 0xa7);
  check("ptPT AltGr 7 ({)", conv(0x24, AltGr, PtPt), '{');
  check("ptPT AltGr 8 ([)", conv(0x25, AltGr, PtPt), '[');
  check("ptPT AltGr 9 (])", conv(0x26, AltGr, PtPt), ']');
  check("ptPT AltGr 0 (})", conv(0x27, AltGr, PtPt), '}');
  check("ptPT AltGr e EUR unicode", convU(0x08, AltGr, PtPt), 0x20ac);

  // fr-CH (Swiss French, Windows KBDSF): AltGr is a distinct level.
  check("frCH AltGr 1 (pipe)", conv(0x1e, AltGr, FrCh), '|');
  check("frCH AltGr 2 (@)", conv(0x1f, AltGr, FrCh), '@');
  check("frCH AltGr 3 (#)", conv(0x20, AltGr, FrCh), '#');
  check("frCH AltGr 7 (broken bar)", conv(0x24, AltGr, FrCh), 0xa6);
  check("frCH AltGr 8 (cent)", conv(0x25, AltGr, FrCh), 0xa2);
  check("frCH AltGr e-grave ([)", conv(0x2f, AltGr, FrCh), '[');
  check("frCH AltGr a-grave ({)", conv(0x34, AltGr, FrCh), '{');
  check("frCH AltGr dollar (})", conv(0x32, AltGr, FrCh), '}');
  check("frCH AltGr dead-key (])", conv(0x30, AltGr, FrCh), ']');
  check("frCH AltGr e EUR unicode", convU(0x08, AltGr, FrCh), 0x20ac);
  // Swiss base digits are unshifted digits.
  check("frCH 1 base", conv(0x1e, 0, FrCh), '1');

  // hu-HU (Windows KBDHU): rich AltGr on letters (programmer symbols) + non-ASCII
  // letters carried in the unicode field only.
  check("huHU AltGr q (backslash)", conv(0x14, AltGr, HuHu), '\\');
  check("huHU AltGr w (pipe)", conv(0x1a, AltGr, HuHu), '|');
  check("huHU AltGr f ([)", conv(0x09, AltGr, HuHu), '[');
  check("huHU AltGr g (])", conv(0x0a, AltGr, HuHu), ']');
  check("huHU AltGr b ({)", conv(0x05, AltGr, HuHu), '{');
  check("huHU AltGr n (})", conv(0x11, AltGr, HuHu), '}');
  check("huHU AltGr v (@)", conv(0x19, AltGr, HuHu), '@');
  check("huHU AltGr x (#)", conv(0x1b, AltGr, HuHu), '#');
  check("huHU AltGr e-acute ($)", conv(0x33, AltGr, HuHu), '$');
  // Non-Latin-1 AltGr: unicode carries it, ascii is 0.
  check("huHU AltGr u EUR unicode", convU(0x18, AltGr, HuHu), 0x20ac);
  check("huHU AltGr u ascii 0", conv(0x18, AltGr, HuHu), 0);
  check("huHU AltGr o-double-acute divide unicode", convU(0x2f, AltGr, HuHu), 0xf7);
  check("huHU o-double-acute base unicode (U+0151)", convU(0x2f, 0, HuHu), 0x151);
  check("huHU o-double-acute base ascii 0", conv(0x2f, 0, HuHu), 0);
  check("huHU u-double-acute base unicode (U+0171)", convU(0x31, 0, HuHu), 0x171);

  // pt-BR (ABNT2, Windows KBDBR): AltGr is the third shift state.
  check("ptBR AltGr 1 (superscript1)", conv(0x1e, AltGr, PtBr), 0xb9);
  check("ptBR AltGr 2 (superscript2)", conv(0x1f, AltGr, PtBr), 0xb2);
  check("ptBR AltGr 3 (superscript3)", conv(0x20, AltGr, PtBr), 0xb3);
  check("ptBR AltGr 4 (pound)", conv(0x21, AltGr, PtBr), 0xa3);
  check("ptBR AltGr 5 (cent)", conv(0x22, AltGr, PtBr), 0xa2);
  check("ptBR AltGr 6 (not-sign)", conv(0x23, AltGr, PtBr), 0xac);
  check("ptBR AltGr q (/)", conv(0x14, AltGr, PtBr), '/');
  check("ptBR AltGr w (?)", conv(0x1a, AltGr, PtBr), '?');
  check("ptBR AltGr e (degree)", conv(0x08, AltGr, PtBr), 0xb0);
  check("ptBR AltGr = (section)", conv(0x2e, AltGr, PtBr), 0xa7);
  check("ptBR AltGr [ (feminine ord)", conv(0x30, AltGr, PtBr), 0xaa);
  check("ptBR AltGr ] (masculine ord)", conv(0x31, AltGr, PtBr), 0xba);
  // Cruzeiro sign (U+20A2) is outside Latin-1: unicode set, ascii 0.
  check("ptBR AltGr c cruzeiro unicode", convU(0x06, AltGr, PtBr), 0x20a2);
  check("ptBR AltGr c ascii 0", conv(0x06, AltGr, PtBr), 0);

  // --- CapsLock (applies only to real cased-letter keys) ---
  // Basic a-z, and Shift cancels CapsLock.
  check("deDE capslock a -> A", conv(0x04, 0, DeDe, true), 'A');
  check("deDE capslock+shift a -> a", conv(0x04, Shift, DeDe, true), 'a');
  // Accented letters get uppercased (previously outside the 0x04-0x1D range).
  check("deDE capslock u-umlaut -> U-umlaut", conv(0x2f, 0, DeDe, true), 0xdc);
  check("deDE capslock+shift u-umlaut -> u-umlaut", conv(0x2f, Shift, DeDe, true), 0xfc);
  check("daDK capslock a-ring -> A-ring", conv(0x2f, 0, DaDk, true), 0xc5);
  // German ß: a letter but Shift is '?', not an uppercase -> CapsLock no-op.
  check("deDE capslock eszett stays eszett", conv(0x2d, 0, DeDe, true), 0xdf);
  // AZERTY: 'm' is at usage 0x33 (outside the old range) -> now uppercased.
  check("frFR capslock m -> M", conv(0x33, 0, FrFr, true), 'M');
  check("frFR capslock a-position -> A", conv(0x04, 0, FrFr, true), 'Q'); // AZERTY 0x04 = q/Q
  check("frFR capslock q-position -> A", conv(0x14, 0, FrFr, true), 'A'); // AZERTY 0x14 = a/A
  // AZERTY comma key (usage 0x10, inside old range) is NOT a letter -> no-op.
  check("frFR capslock comma-key stays ','", conv(0x10, 0, FrFr, true), ',');
  // Digits/symbols never affected by CapsLock.
  check("deDE capslock 1 stays 1", conv(0x1e, 0, DeDe, true), '1');
  // CapsLock does not disturb the AltGr layer.
  check("deDE capslock + AltGr q still @", conv(0x14, AltGr, DeDe, true), '@');

  if (failures != 0)
  {
    std::printf("%d check(s) failed\n", failures);
    return 1;
  }
  std::puts("OK - all keymap checks passed");
  return 0;
}
