// Host-side unit tests for the HID usage -> 8-bit character conversion.
//
// This file is compiled and run on the host with g++ (no board required) by
// test_keymap.py. The layout enum, the keymap include list, and the two pure
// conversion functions (espUsbHostKeycodeToAscii / espUsbHostKeypadKeycodeToAscii)
// are extracted verbatim from the real library sources at test time and written
// to "espusbhost_keymap_real.h" in the build output directory, so these checks
// exercise the actual production tables and conversion logic - not a copy.
//
// Expected values follow each layout's national standard (Windows layout data;
// non-ASCII in ISO-8859-1, dead keys produce 0).

#include <cstdint>
#include <cstddef>
#include <cstdio>

// Generated by test_keymap.py: enum + keymap tables + conversion functions,
// all extracted from src/EspUsbHost.h and src/EspUsbHostHid.cpp.
#include "espusbhost_keymap_real.h"

namespace
{
int failures = 0;
constexpr uint8_t Shift = 0x02; // Left Shift modifier bit

void check(const char *name, unsigned actual, unsigned expected)
{
  if (actual != expected)
  {
    std::printf("FAIL %-42s got 0x%02x expected 0x%02x\n", name, actual, expected);
    ++failures;
  }
}

uint8_t conv(
    uint8_t keycode,
    uint8_t modifiers,
    EspUsbHostKeyboardLayout layout,
    bool capsLock = false,
    bool numLock = false)
{
  return espUsbHostKeycodeToAscii(keycode, modifiers, layout, capsLock, numLock);
}
} // namespace

int main()
{
  const auto EnUs = ESP_USB_HOST_KEYBOARD_LAYOUT_EN_US;
  const auto JaJp = ESP_USB_HOST_KEYBOARD_LAYOUT_JA_JP;
  const auto NlNl = ESP_USB_HOST_KEYBOARD_LAYOUT_NL_NL;
  const auto PtBr = ESP_USB_HOST_KEYBOARD_LAYOUT_PT_BR;

  // Keypad handling is layout-independent.
  check("keypad / (numlock off)", conv(0x54, 0, EnUs, false, false), '/');
  check("keypad 1 (numlock on)", conv(0x59, 0, EnUs, false, true), '1');
  check("keypad 1 (numlock off)", conv(0x59, 0, EnUs, false, false), 0);

  // Guard: only extended layouts (ja_jp, pt_BR) may reach usage >= 0x80,
  // and never beyond 0x8f. Everything else above 0x7f returns 0.
  check("enUS out of range 0x87", conv(0x87, 0, EnUs), 0);
  check("ptBR out of range 0x90", conv(0x90, 0, PtBr), 0);
  check("jaJP out of range 0x90", conv(0x90, 0, JaJp), 0);

  // ja-JP (JIS). Comment-only fix upstream; data must be unchanged.
  check("jaJP shift 2", conv(0x1f, Shift, JaJp), '"');
  check("jaJP ro", conv(0x87, 0, JaJp), '\\');
  check("jaJP shift ro", conv(0x87, Shift, JaJp), '_');
  check("jaJP yen", conv(0x89, 0, JaJp), '\\');
  check("jaJP shift yen", conv(0x89, Shift, JaJp), '|');

  // nl-NL (Dutch, Windows KBDNE). Digit row shift characters.
  check("nlNL shift 2", conv(0x1f, Shift, NlNl), '"');
  check("nlNL shift 6", conv(0x23, Shift, NlNl), '&');
  check("nlNL shift 7", conv(0x24, Shift, NlNl), '_');
  check("nlNL shift 8", conv(0x25, Shift, NlNl), '(');
  check("nlNL shift 9", conv(0x26, Shift, NlNl), ')');
  check("nlNL shift 0", conv(0x27, Shift, NlNl), '\'');
  // Symbol keys.
  check("nlNL minus position", conv(0x2d, 0, NlNl), '/');
  check("nlNL shift minus position", conv(0x2d, Shift, NlNl), '?');
  check("nlNL equals position (degree)", conv(0x2e, 0, NlNl), 0xb0);
  check("nlNL shift equals (dead ~)", conv(0x2e, Shift, NlNl), 0);
  check("nlNL [ position (dead trema)", conv(0x2f, 0, NlNl), 0);
  check("nlNL ] position", conv(0x30, 0, NlNl), '*');
  check("nlNL shift ] position", conv(0x30, Shift, NlNl), '|');
  check("nlNL NUHS", conv(0x32, 0, NlNl), '<');
  check("nlNL shift NUHS", conv(0x32, Shift, NlNl), '>');
  check("nlNL ; position", conv(0x33, 0, NlNl), '+');
  check("nlNL shift ; position (plus-minus)", conv(0x33, Shift, NlNl), 0xb1);
  check("nlNL ' position (dead acute)", conv(0x34, 0, NlNl), 0);
  check("nlNL grave position", conv(0x35, 0, NlNl), '@');
  check("nlNL shift grave (section)", conv(0x35, Shift, NlNl), 0xa7);
  check("nlNL shift comma", conv(0x36, Shift, NlNl), ';');
  check("nlNL shift period", conv(0x37, Shift, NlNl), ':');
  check("nlNL slash position", conv(0x38, 0, NlNl), '-');
  check("nlNL shift slash position", conv(0x38, Shift, NlNl), '=');
  check("nlNL NUBS", conv(0x64, 0, NlNl), ']');
  check("nlNL shift NUBS", conv(0x64, Shift, NlNl), '[');

  // pt-BR (ABNT2). The previously-broken keys: International1 (/ and ?) and the
  // numpad comma, plus the cedilla and the slash-key-that-stays-semicolon.
  check("ptBR cedilla", conv(0x33, 0, PtBr), 0xe7);
  check("ptBR shift cedilla", conv(0x33, Shift, PtBr), 0xc7);
  check("ptBR slash key stays ;", conv(0x38, 0, PtBr), ';');
  check("ptBR shift slash key stays :", conv(0x38, Shift, PtBr), ':');
  check("ptBR International1 /", conv(0x87, 0, PtBr), '/');
  check("ptBR shift International1 ?", conv(0x87, Shift, PtBr), '?');
  check("ptBR keypad comma", conv(0x85, 0, PtBr), ',');

  if (failures != 0)
  {
    std::printf("%d check(s) failed\n", failures);
    return 1;
  }
  std::puts("OK - all keymap checks passed");
  return 0;
}
