"""Host-side unit test for the keymap tables and the HID->ASCII conversion.

The conversion logic lives in ``src/EspUsbHostHid.cpp``, which pulls in
``Arduino.h`` and the ESP USB host stack and therefore cannot be compiled on the
host directly. Rather than duplicate the logic (which would let the test and the
library drift apart), this test extracts the pieces it needs straight from the
real sources at run time:

* the ``EspUsbHostKeyboardLayout`` enum from ``src/EspUsbHost.h``
* the ``#include "keymap/..."`` list, the ``MOD_*`` constants, and the two pure
  functions (``espUsbHostKeypadKeycodeToAscii`` / ``espUsbHostKeycodeToAscii``)
  from ``src/EspUsbHostHid.cpp``

These are concatenated into ``output/espusbhost_keymap_real.h`` and compiled
together with ``keymap_test.cpp``. The assertions thus run against the actual
production tables and conversion code.
"""

import re
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / ".." / ".." / ".." / "src"


def _brace_match(text: str, signature: str) -> str:
    """Return the full definition (signature + body) for a function, located by
    a substring of its signature and delimited by brace matching."""
    start = text.index(signature)
    open_brace = text.index("{", start)
    depth = 0
    for i in range(open_brace, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]
    raise AssertionError(f"unbalanced braces after {signature!r}")


def _generate_real_header(dest: Path) -> None:
    host_h = (SRC / "EspUsbHost.h").read_text()
    hid_cpp = (SRC / "EspUsbHostHid.cpp").read_text()

    enum_match = re.search(
        r"enum EspUsbHostKeyboardLayout\s*:\s*\w+\s*\{.*?\};", host_h, re.S
    )
    assert enum_match, "EspUsbHostKeyboardLayout enum not found in EspUsbHost.h"

    keymap_includes = re.findall(r'^#include "keymap/[^"]+"', hid_cpp, re.M)
    assert keymap_includes, "no keymap includes found in EspUsbHostHid.cpp"

    mod_consts = re.findall(
        r"^static constexpr uint8_t MOD_[A-Z_]+ = 0x[0-9a-fA-F]+;", hid_cpp, re.M
    )
    assert mod_consts, "MOD_* constants not found in EspUsbHostHid.cpp"

    keypad_fn = _brace_match(hid_cpp, "uint8_t espUsbHostKeypadKeycodeToAscii(")
    unicode_fn = _brace_match(hid_cpp, "uint16_t espUsbHostKeycodeToUnicode(")
    ascii_fn = _brace_match(hid_cpp, "uint8_t espUsbHostKeycodeToAscii(")

    parts = [
        "// GENERATED by test_keymap.py from src/EspUsbHost.h and",
        "// src/EspUsbHostHid.cpp. Do not edit; do not commit.",
        "#pragma once",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        enum_match.group(0),
        "",
        *keymap_includes,
        "",
        *mod_consts,
        "",
        keypad_fn,
        "",
        unicode_fn,  # must precede the ascii wrapper, which calls it
        "",
        ascii_fn,
        "",
    ]
    dest.write_text("\n".join(parts))


def test_keymap_conversion(build_and_run):
    output = HERE / "output"
    output.mkdir(exist_ok=True)
    _generate_real_header(output / "espusbhost_keymap_real.h")

    print(build_and_run(
        "keymap_test.cpp",
        includes=[
            output,         # espusbhost_keymap_real.h
            SRC,            # keymap/*.h tables
            HERE / "stub",  # class/hid/hid.h stub
        ],
        # Match the Xtensa toolchain, where plain char is unsigned. The host's is
        # signed, so without this the tables would be indexed differently here
        # than on the board.
        extra_flags=["-funsigned-char"],
    ))
