"""Host-side unit test for the USB Video decoding and stream-selection helpers.

The helpers are ``inline`` free functions in ``src/EspUsbHost.h``, but that header
pulls in Arduino and the ESP USB host stack and cannot be compiled on the host.
Like the audio test, this one extracts the pieces it needs from the real source
at run time instead of duplicating them, so the assertions run against the
production code:

* the ``ESP_USB_HOST_MAX_VIDEO_*``, ``ESP_USB_HOST_VIDEO_FORMAT_*`` and
  ``ESP_USB_HOST_VIDEO_PROBE_*`` constants
* ``struct EspUsbHostVideoStreamInfo``, ``EspUsbHostVideoStreamSelection``,
  ``EspUsbHostVideoPayloadHeader`` and ``EspUsbHostVideoProbeControl``
* every ``espUsbHostVideo*`` helper used by the descriptor, payload-header and
  Probe/Commit paths, plus the selection helpers that ``videoStart()`` delegates
  to

These are concatenated into ``output/espusbhost_video_real.h`` and compiled with
``video_uvc_test.cpp``.
"""

import re
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / ".." / ".." / ".." / "src"

# Extracted in this order: later helpers call earlier ones.
FUNCTIONS = [
    "inline uint16_t espUsbHostVideoReadU16(",
    "inline uint32_t espUsbHostVideoReadU32(",
    "inline void espUsbHostVideoWriteU16(",
    "inline void espUsbHostVideoWriteU32(",
    "inline uint8_t espUsbHostVideoFormatFromGuid(",
    "inline const char *espUsbHostVideoFormatName(",
    "inline uint32_t espUsbHostVideoFrameIntervalToFps(",
    "inline uint32_t espUsbHostVideoFpsToFrameInterval(",
    "inline uint8_t espUsbHostVideoIsocTransactions(",
    "inline uint32_t espUsbHostVideoIsocPayloadSize(",
    "inline bool espUsbHostVideoDecodeFormatDescriptor(",
    "inline bool espUsbHostVideoDecodeFrameDescriptor(",
    "inline bool espUsbHostVideoStreamSupportsFrameInterval(",
    "inline uint32_t espUsbHostVideoStreamNearestFrameInterval(",
    "inline int espUsbHostVideoStreamScore(",
    "inline EspUsbHostVideoStreamSelection espUsbHostSelectVideoStream(",
    "inline bool espUsbHostVideoDecodePayloadHeader(",
    "inline size_t espUsbHostVideoEncodeProbeControl(",
    "inline bool espUsbHostVideoDecodeProbeControl(",
]

STRUCTS = [
    "EspUsbHostVideoStreamInfo",
    "EspUsbHostVideoStreamSelection",
    "EspUsbHostVideoPayloadHeader",
    "EspUsbHostVideoProbeControl",
]

CONSTANTS = [
    "ESP_USB_HOST_MAX_VIDEO_STREAMS",
    "ESP_USB_HOST_MAX_VIDEO_FRAME_INTERVALS",
    "ESP_USB_HOST_VIDEO_FORMAT_UNKNOWN",
    "ESP_USB_HOST_VIDEO_FORMAT_MJPEG",
    "ESP_USB_HOST_VIDEO_FORMAT_YUY2",
    "ESP_USB_HOST_VIDEO_FORMAT_NV12",
    "ESP_USB_HOST_VIDEO_FORMAT_H264",
    "ESP_USB_HOST_VIDEO_FORMAT_UNCOMPRESSED",
    "ESP_USB_HOST_VIDEO_PROBE_LENGTH_10",
    "ESP_USB_HOST_VIDEO_PROBE_LENGTH_11",
    "ESP_USB_HOST_VIDEO_PROBE_MAX_LENGTH",
]


def _brace_match(text: str, signature: str) -> str:
    """Return the full definition (signature + body) for a declaration, located by
    a substring of its signature and delimited by brace matching."""
    start = text.index(signature)
    open_brace = text.index("{", start)
    depth = 0
    for i in range(open_brace, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                end = text.index(";", i) + 1 if text[start:].startswith("struct") else i + 1
                return text[start:end]
    raise AssertionError(f"unbalanced braces after {signature!r}")


def _generate_real_header(dest: Path) -> None:
    host_h = (SRC / "EspUsbHost.h").read_text()

    parts = [
        "// GENERATED by test_video_uvc.py from src/EspUsbHost.h.",
        "// Do not edit; do not commit.",
        "#pragma once",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
    ]

    for name in CONSTANTS:
        match = re.search(
            r"^static constexpr \w+ " + name + r" = [^;]+;", host_h, re.M
        )
        assert match, f"{name} not found in EspUsbHost.h"
        parts.append(match.group(0))
    parts.append("")

    for name in STRUCTS:
        parts.append(_brace_match(host_h, f"struct {name}\n"))
        parts.append("")

    for signature in FUNCTIONS:
        parts.append(_brace_match(host_h, signature))
        parts.append("")

    dest.write_text("\n".join(parts))


def test_video_uvc_decoding(build_and_run):
    output = HERE / "output"
    output.mkdir(exist_ok=True)
    _generate_real_header(output / "espusbhost_video_real.h")

    print(build_and_run(
        "video_uvc_test.cpp",
        includes=[output],  # espusbhost_video_real.h
    ))
