/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef ESPUSBHOST_VERSION_H
#define ESPUSBHOST_VERSION_H

#define ESPUSBHOST_VERSION_MAJOR 2
#define ESPUSBHOST_VERSION_MINOR 1
#define ESPUSBHOST_VERSION_PATCH 0
#define ESPUSBHOST_VERSION_STR "2.1.0"

#endif // ESPUSBHOST_VERSION_H
