/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef ESPUSBHOST_VERSION_H
#define ESPUSBHOST_VERSION_H

#define ESPUSBHOST_VERSION_MAJOR 2
#define ESPUSBHOST_VERSION_MINOR 7
#define ESPUSBHOST_VERSION_PATCH 9
#define ESPUSBHOST_VERSION_STR "2.7.9"

#endif // ESPUSBHOST_VERSION_H
